### ISSUE TITLE
pip 無法安裝

### ISSUE THREAD

**Issue by alenweiru** [i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7#642]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\weiru\AppData\Local\Temp\pip-install-gd39u80y\tai5-uan5-gian5-gi2-kang1-ku7\setup.py", line 59, in <module>
        'pydub',
      File "C:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
        self.find_sources()
      File "C:\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
        mm.run()
      File "C:\Anaconda3\lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.read_template()
      File "C:\Anaconda3\lib\distutils\command\sdist.py", line 337, in read_template
        line = template.readline()
      File "C:\Anaconda3\lib\distutils\text_file.py", line 175, in readline
        line = self.file.readline()
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe8 in position 18: illegal multibyte sequence

**Comment by sih4sing5hong5** [comment]
感覺是windows 編碼ê問題 ： https://coder.tw/?p=7487

**Comment by alenweiru** [comment]
你好~我再在尋找台語轉羅馬拼音的開源工具,不知道您是否可以給一些建意

薛丞宏 <notifications@github.com> 於 2019年6月17日 週一 下午10:16寫道：

**Comment by alenweiru** [comment]
你好~我再在尋找台語轉羅馬拼音的開源工具,不知道您是否可以給一些建意
