### ISSUE TITLE
看語句有問題

### ISSUE THREAD

**Issue by niauah** [i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7#672]
羅馬字='gún-tau ê tiān-uē hō-bé sī khòng ngóo - tshit khòng it pat it it ngóo'
減號提掉就無問題

Traceback (most recent call last):
  ...
  File "/home/khing-iong/git/PakKhooTai-KauTui/kautui/autai/management/commands/giliau_csv.py", line 55, in handle
    數字聲調, 白話字 = self.sng_soojitiau_poj(tsua['羅馬字'])
  File "/home/khing-iong/git/PakKhooTai-KauTui/kautui/autai/management/commands/giliau_csv.py", line 98, in sng_soojitiau_poj
    soojitiau = ku.轉音(臺灣閩南語羅馬字拼音).看語句()
  File "/home/khing-iong/git/PakKhooTai-KauTui/kautui/venv/lib/python3.6/site-packages/臺灣言語工具/基本物件/句.py", line 48, in 看語句
    集的型.append(一集.看語句())
  File "/home/khing-iong/git/PakKhooTai-KauTui/kautui/venv/lib/python3.6/site-packages/臺灣言語工具/基本物件/集.py", line 41, in 看語句
    return self.內底組[0].看語句()
  File "/home/khing-iong/git/PakKhooTai-KauTui/kautui/venv/lib/python3.6/site-packages/臺灣言語工具/基本物件/組.py", line 47, in 看語句
    and (敢是拼音字元(詞型[0]) or 詞型[0].isdigit() or 詞型[0] == 分字符號)
IndexError: string index out of range

**Comment by niauah** [comment]
'Tsit-kuá iâm kín lā kún-tsuí lim-- lo̍h-khì.'

這句mā是
